[2019-11-18 16:12:59,586] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/user?page=1 HTTP/1.1" 200 0
[2019-11-18 16:12:59,694] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:12:59,764] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/user?page=1 HTTP/1.1" 200 0
[2019-11-18 16:12:59,774] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:06,738] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:07,190] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:07,351] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:07,521] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:07,737] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:07,895] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:08,053] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:08,231] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:08,368] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:08,531] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:08,681] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:08,850] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:08,994] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:09,140] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:09,288] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:09,424] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:09,565] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:13:09,756] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:15:59,238] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:16:48,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:17:05,938] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:17:09,353] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/user HTTP/1.1" 200 0
[2019-11-18 16:17:09,364] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:17:09,445] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:17:10,949] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:17:10,977] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:34,821] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:19:37,880] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:37,955] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:38,950] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:38,984] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:39,190] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:39,233] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:39,377] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:39,415] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:39,556] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:39,586] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:39,740] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:39,782] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:39,902] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:39,933] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:40,072] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:40,112] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:40,232] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:40,275] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:19:45,019] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.TUser_View didn't return an HttpResponse object. It returned None instead.
[2019-11-18 16:19:45,057] [basehttp.py:124] [basehttp:log_message] [ERROR]- "DELETE /v1/users/user HTTP/1.1" 500 63188
[2019-11-18 16:20:58,938] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:21:01,852] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:21:01,863] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:21:15,812] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:21:17,982] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:21:17,994] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:21:45,802] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:21:48,267] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:21:48,277] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:22:59,642] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:23:01,864] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:23:01,871] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:23:05,587] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:23:05,600] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:23:08,151] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:23:08,161] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:24:07,232] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:24:09,181] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:24:09,191] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 362
[2019-11-18 16:27:21,057] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:27:21,470] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:27:21,696] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:27:21,945] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:27:23,225] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:28:01,650] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:30:09,779] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:30:10,613] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 16:30:12,531] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:30:12,546] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 229
[2019-11-18 16:30:14,044] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 229
[2019-11-18 16:31:07,617] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 229
[2019-11-18 16:31:09,647] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:10,710] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 16:31:16,568] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:16,579] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 219
[2019-11-18 16:31:27,246] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:27,254] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 389
[2019-11-18 16:31:33,173] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:33,191] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 559
[2019-11-18 16:31:37,673] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:37,685] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 729
[2019-11-18 16:31:39,525] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:40,290] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 559
[2019-11-18 16:31:42,332] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 559
[2019-11-18 16:31:42,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 559
[2019-11-18 16:31:42,984] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 559
[2019-11-18 16:31:43,220] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 559
[2019-11-18 16:31:47,555] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:48,302] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 389
[2019-11-18 16:31:49,405] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 389
[2019-11-18 16:31:52,933] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:53,826] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 219
[2019-11-18 16:31:54,803] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 219
[2019-11-18 16:31:58,042] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:31:58,607] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 16:32:00,443] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 16:32:04,986] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:32:04,998] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 241
[2019-11-18 16:32:09,573] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:32:09,580] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 436
[2019-11-18 16:32:13,807] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:32:13,823] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 636
[2019-11-18 16:32:17,409] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:32:17,424] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 802
[2019-11-18 16:32:22,894] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:32:22,902] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 974
[2019-11-18 16:32:26,695] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:32:26,711] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 1141
[2019-11-18 16:32:39,342] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:32:41,533] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 949
[2019-11-18 16:33:13,290] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 949
[2019-11-18 16:33:17,241] [views.py:90] [views:delete] [ERROR]- 删除异常：'TUser' object is not iterable
[2019-11-18 16:33:17,243] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 50
[2019-11-18 16:33:48,102] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 949
[2019-11-18 16:33:50,800] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:33:51,939] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 388
[2019-11-18 16:33:52,890] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 388
[2019-11-18 16:34:56,837] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 388
[2019-11-18 16:34:57,358] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 388
[2019-11-18 16:34:57,554] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 388
[2019-11-18 16:34:57,741] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 388
[2019-11-18 16:34:57,929] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 388
[2019-11-18 16:35:12,946] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:35:12,964] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 556
[2019-11-18 16:37:37,134] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 592
[2019-11-18 16:37:54,778] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:37:55,652] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 16:37:59,238] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:37:59,247] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 227
[2019-11-18 16:38:02,682] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:38:03,390] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 16:38:07,025] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 16:38:07,040] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 229
[2019-11-18 16:46:46,827] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 5185
[2019-11-18 16:46:46,848] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[2019-11-18 16:46:46,856] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2019-11-18 16:46:47,022] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 5185
[2019-11-18 16:46:47,220] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2019-11-18 16:46:47,254] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[2019-11-18 16:46:47,295] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[2019-11-18 16:46:47,496] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[2019-11-18 16:46:47,497] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[2019-11-18 16:46:47,497] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[2019-11-18 16:46:47,529] [base.py:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
[2019-11-18 16:46:47,530] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2297
[2019-11-18 16:46:49,317] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 3055
[2019-11-18 16:46:49,338] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:46:49,356] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2019-11-18 16:46:49,421] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[2019-11-18 16:46:49,421] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2019-11-18 16:46:49,423] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2019-11-18 16:46:49,424] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2019-11-18 16:46:49,424] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2019-11-18 16:46:49,438] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2019-11-18 16:46:49,470] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[2019-11-18 16:46:49,470] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
[2019-11-18 16:46:49,528] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[2019-11-18 16:46:50,921] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/add/ HTTP/1.1" 200 5419
[2019-11-18 16:46:50,940] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:46:50,947] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[2019-11-18 16:46:50,958] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[2019-11-18 16:46:50,958] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[2019-11-18 16:46:50,976] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[2019-11-18 16:47:01,413] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/trole/add/ HTTP/1.1" 200 5594
[2019-11-18 16:47:01,435] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:14,705] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 3055
[2019-11-18 16:47:14,725] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:15,252] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2592
[2019-11-18 16:47:15,499] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2592
[2019-11-18 16:47:16,251] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 3055
[2019-11-18 16:47:16,268] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:16,649] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 3055
[2019-11-18 16:47:16,664] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:18,137] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2592
[2019-11-18 16:47:18,929] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 3057
[2019-11-18 16:47:18,951] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:20,120] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4358
[2019-11-18 16:47:20,139] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:24,202] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 16:47:24,336] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 4762
[2019-11-18 16:47:24,357] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:24,417] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[2019-11-18 16:47:25,987] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4358
[2019-11-18 16:47:27,257] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2592
[2019-11-18 16:47:28,762] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 4587
[2019-11-18 16:47:28,787] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:31,835] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2592
[2019-11-18 16:47:32,673] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 3055
[2019-11-18 16:47:32,690] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:33,543] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/add/ HTTP/1.1" 200 5993
[2019-11-18 16:47:33,559] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:42,980] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/trole/add/ HTTP/1.1" 302 0
[2019-11-18 16:47:43,014] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5379
[2019-11-18 16:47:43,030] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:47:44,733] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5213
[2019-11-18 16:47:44,755] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 16:48:08,112] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 243
[2019-11-18 16:48:08,490] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 243
[2019-11-18 16:48:08,694] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 243
[2019-11-18 16:48:45,761] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 16:57:12,781] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 16:57:13,251] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:08:26,427] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/right?page=1 HTTP/1.1" 200 0
[2019-11-18 17:08:26,436] [LinqHelper.py:53] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'is_active' into field. Choices are: id, parent, right_name, trole
[2019-11-18 17:08:26,436] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 115, in get
    res['data'] = LinqHelper.res_format(code, data.page(page).object_list)['data']
AttributeError: 'str' object has no attribute 'page'
[2019-11-18 17:08:26,504] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right?page=1 HTTP/1.1" 500 82970
[2019-11-18 17:08:27,583] [LinqHelper.py:53] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'is_active' into field. Choices are: id, parent, right_name, trole
[2019-11-18 17:08:27,583] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 115, in get
    res['data'] = LinqHelper.res_format(code, data.page(page).object_list)['data']
AttributeError: 'str' object has no attribute 'page'
[2019-11-18 17:08:27,620] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right?page=1 HTTP/1.1" 500 82970
[2019-11-18 17:08:32,229] [LinqHelper.py:53] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'is_active' into field. Choices are: id, parent, right_name, trole
[2019-11-18 17:08:32,230] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 115, in get
    res['data'] = LinqHelper.res_format(code, data.page(page).object_list)['data']
AttributeError: 'str' object has no attribute 'page'
[2019-11-18 17:08:32,298] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right?page=1 HTTP/1.1" 500 82970
[2019-11-18 17:08:33,768] [LinqHelper.py:53] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'is_active' into field. Choices are: id, parent, right_name, trole
[2019-11-18 17:08:33,769] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 115, in get
    res['data'] = LinqHelper.res_format(code, data.page(page).object_list)['data']
AttributeError: 'str' object has no attribute 'page'
[2019-11-18 17:08:33,819] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right?page=1 HTTP/1.1" 500 82970
[2019-11-18 17:09:23,938] [LinqHelper.py:53] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'is_active' into field. Choices are: id, parent, right_name, trole
[2019-11-18 17:09:23,939] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 116, in get
    res['data'] = LinqHelper.res_format(code, data.page(page).object_list)['data']
AttributeError: 'str' object has no attribute 'page'
[2019-11-18 17:09:24,021] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right?page=1 HTTP/1.1" 500 82960
[2019-11-18 17:09:41,105] [LinqHelper.py:53] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'is_active' into field. Choices are: id, parent, right_name, trole
[2019-11-18 17:09:41,106] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 117, in get
    res['data'] = LinqHelper.res_format(code, data.page(page).object_list)['data']
AttributeError: 'str' object has no attribute 'page'
[2019-11-18 17:09:41,188] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right?page=1 HTTP/1.1" 500 82976
[2019-11-18 17:11:24,790] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:24,792] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:11:25,380] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:25,380] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:11:25,641] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:25,641] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:11:26,739] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:26,740] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:11:26,962] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:26,963] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:11:27,192] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:27,193] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:11:27,439] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:27,439] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:11:44,577] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:11:44,578] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:12:04,659] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:12:04,659] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:12:05,359] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/right
[2019-11-18 17:12:05,359] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/right?page=1 HTTP/1.1" 404 2366
[2019-11-18 17:12:18,966] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:12:19,683] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:12:20,496] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:28,418] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:28,912] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:29,107] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:29,335] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:29,567] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:30,582] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:30,960] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:31,218] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:13:37,543] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/user?page=1 HTTP/1.1" 200 0
[2019-11-18 17:15:03,567] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:15:05,103] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:15:05,401] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:15:05,666] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:15:05,890] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:15:10,201] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/user HTTP/1.1" 200 0
[2019-11-18 17:15:10,224] [views.py:70] [views:post] [ERROR]- 添加失败：(1048, "Column 'tRole_id' cannot be null")
[2019-11-18 17:15:10,226] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 17:17:05,123] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:17:09,197] [views.py:70] [views:post] [ERROR]- 添加失败：(1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')
[2019-11-18 17:17:09,198] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 17:18:23,880] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:18:27,960] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 66, in post
    TUser.objects.create(login_phone=phone, password=password, vername=vername, tRole_id=1)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')
[2019-11-18 17:18:28,098] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 233956
[2019-11-18 17:18:48,195] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:18:55,645] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 66, in post
    TUser.objects.create(login_phone=phone, password=password, vername=vername, tRole_id=1)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')
[2019-11-18 17:18:55,734] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 233936
[2019-11-18 17:20:07,380] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:20:13,497] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 67, in post
    TUser.objects.create(login_phone=phone, password=password, vername=vername, tRole=TRole.objects.get(id=1))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: TRole matching query does not exist.
[2019-11-18 17:20:13,574] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 91438
[2019-11-18 17:22:01,434] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:22:04,403] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 67, in post
    print(TRole.objects.get(id=1))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: TRole matching query does not exist.
[2019-11-18 17:22:04,491] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 91310
[2019-11-18 17:22:22,156] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:22:26,618] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 67, in post
    TUser.objects.create(login_phone=phone, password=password, vername=vername, tRole_id=1)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')
[2019-11-18 17:22:26,733] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 233901
[2019-11-18 17:24:12,280] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:12,513] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:12,746] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:12,941] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:13,049] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:13,396] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:13,561] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:13,659] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:24:13,871] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:25:56,418] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:25:58,154] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:25:58,505] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:25:58,771] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:25:59,002] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:26:01,586] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 68, in post
    is_active=TUser)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1111, in execute_sql
    for sql, params in self.as_sql():
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in as_sql
    for obj in self.query.objs
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in <listcomp>
    for obj in self.query.objs
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1003, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 770, in get_db_prep_save
    prepared=False)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 762, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1043, in get_prep_value
    return self.to_python(value)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1036, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["’<class 'users.models.TUser'>‘ 必须为 True 或者 False。"]
[2019-11-18 17:26:01,717] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 163322
[2019-11-18 17:26:11,958] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 68, in post
    is_active=TUser)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1111, in execute_sql
    for sql, params in self.as_sql():
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in as_sql
    for obj in self.query.objs
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in <listcomp>
    for obj in self.query.objs
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1003, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 770, in get_db_prep_save
    prepared=False)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 762, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1043, in get_prep_value
    return self.to_python(value)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1036, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["’<class 'users.models.TUser'>‘ 必须为 True 或者 False。"]
[2019-11-18 17:26:12,015] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 162708
[2019-11-18 17:27:09,940] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 51
[2019-11-18 17:27:12,045] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/user
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 68, in post
    is_active=True)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`storage`.`users_tuser`, CONSTRAINT `users_tuser_tRole_id_b01b7d65_fk_users_trole_id` FOREIGN KEY (`tRole_id`) REFERENCES `users_trole` (`id`))')
[2019-11-18 17:27:12,158] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /v1/users/user HTTP/1.1" 500 233937
[2019-11-18 17:36:53,572] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:36:54,573] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:36:54,909] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:36:59,936] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:00,306] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:00,552] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:00,786] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:00,968] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:01,190] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:01,459] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:34,455] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:34,940] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:35,138] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:37:43,072] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 17:37:46,451] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 17:37:49,983] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 80
[2019-11-18 17:37:51,644] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 17:37:59,773] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 80
[2019-11-18 17:38:12,692] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 80
[2019-11-18 17:38:17,406] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 400
[2019-11-18 17:38:29,059] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 80
[2019-11-18 17:39:03,753] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 17:39:04,760] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:39:05,399] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:39:05,952] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:39:06,232] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 201
[2019-11-18 17:39:10,169] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 13
[2019-11-18 17:39:10,182] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:39:24,350] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:39:28,393] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 17:41:00,594] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:01,114] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:01,364] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:01,597] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:01,849] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:02,031] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:02,232] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:02,464] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:41:02,719] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:04,778] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:05,433] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:12,053] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:12,322] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:12,692] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:12,850] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:13,008] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:13,172] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:13,346] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:44:13,685] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:46:48,323] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:46:59,090] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 17:47:00,687] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:47:05,200] [basehttp.py:124] [basehttp:log_message] [INFO]- "DELETE /v1/users/user HTTP/1.1" 200 13
[2019-11-18 17:47:05,880] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:47:59,941] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:48:20,961] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:48:29,494] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:48:52,746] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:49:00,760] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 80
[2019-11-18 17:49:53,545] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:50:00,132] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 17:52:15,011] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 17:53:16,833] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 17:53:25,250] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 17:54:10,784] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:03:05,557] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2019-11-18 18:03:05,615] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
[2019-11-18 18:03:05,645] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/login.css HTTP/1.1" 304 0
[2019-11-18 18:03:06,465] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2019-11-18 18:03:06,494] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
[2019-11-18 18:03:46,557] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
[2019-11-18 18:03:52,595] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2019-11-18 18:03:52,697] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 5697
[2019-11-18 18:03:54,976] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 4586
[2019-11-18 18:03:55,008] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:22,654] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:22,680] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:23,334] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:23,359] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:23,660] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:23,683] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:23,891] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:23,917] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:24,118] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:24,145] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:24,374] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:24,398] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:25,131] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:25,160] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:25,398] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:25,424] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:26,728] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:26,754] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:33,305] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/add/ HTTP/1.1" 200 5993
[2019-11-18 18:05:34,994] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:40,462] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/add/ HTTP/1.1" 200 5993
[2019-11-18 18:05:40,497] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:46,828] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:47,626] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/add/ HTTP/1.1" 200 5993
[2019-11-18 18:05:48,968] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:05:49,873] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2988
[2019-11-18 18:05:53,200] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 4586
[2019-11-18 18:05:53,234] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:05:58,363] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/users/tright/
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1568, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1286, in response_action
    response = func(self, request, queryset)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/actions.py", line 37, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 172, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 232, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 216, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 216, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 218, in _nested
    ret = [format_callback(obj)]
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 145, in format_callback
    force_text(obj))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/home/tarena/桌面/git/Storage/server/storage/users/models.py", line 41, in __str__
    return self.name
AttributeError: 'TUser' object has no attribute 'name'
[2019-11-18 18:05:58,509] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /admin/users/tright/ HTTP/1.1" 500 156081
[2019-11-18 18:06:00,157] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 4586
[2019-11-18 18:06:06,496] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4358
[2019-11-18 18:06:06,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:06:18,445] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:06:18,480] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:06:18,507] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:06:21,071] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:06:21,099] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:06:21,119] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:06:23,081] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:06:23,116] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:06:23,143] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:06:25,176] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:06:25,214] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:06:25,241] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:06:35,703] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 5713
[2019-11-18 18:06:35,725] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:06:39,323] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4358
[2019-11-18 18:06:39,350] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:06:58,341] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:06:58,371] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:06:58,394] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:07:05,887] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:07:05,916] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:07:05,941] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:07:13,682] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:07:13,708] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:07:13,734] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:07:16,820] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 6577
[2019-11-18 18:07:16,840] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:07:20,787] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4358
[2019-11-18 18:07:20,815] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:07:36,265] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:07:36,304] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4586
[2019-11-18 18:07:36,340] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:07:54,613] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:07:54,642] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:07:54,670] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:08:02,400] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:08:02,431] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:08:02,457] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:08:19,515] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:08:19,543] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:08:19,564] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:08:30,028] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:08:30,062] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:08:30,085] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:08:41,265] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2988
[2019-11-18 18:08:44,159] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 8045
[2019-11-18 18:08:44,182] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:09:36,109] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 8497
[2019-11-18 18:09:36,130] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:09:37,708] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?parent=3 HTTP/1.1" 200 6452
[2019-11-18 18:09:37,736] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:10:04,886] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2988
[2019-11-18 18:10:07,141] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 8497
[2019-11-18 18:10:07,167] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:10:11,465] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4358
[2019-11-18 18:10:11,494] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:10:20,521] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 8497
[2019-11-18 18:10:25,146] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4358
[2019-11-18 18:10:25,175] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:10:32,548] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:10:32,581] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:10:32,604] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:10:39,759] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:10:39,786] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:10:39,806] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:10:45,415] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:10:45,452] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:10:45,474] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:10:54,166] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:10:54,195] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:10:54,219] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:00,144] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:11:00,179] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:11:00,207] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:06,764] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:11:06,794] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:11:06,817] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:16,762] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/add/ HTTP/1.1" 302 0
[2019-11-18 18:11:16,797] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/add/ HTTP/1.1" 200 4587
[2019-11-18 18:11:16,825] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:36,298] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 10576
[2019-11-18 18:11:36,333] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:44,055] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 10576
[2019-11-18 18:11:44,098] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:45,407] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2988
[2019-11-18 18:11:46,698] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tuser/ HTTP/1.1" 200 5703
[2019-11-18 18:11:46,723] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:50,116] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/ HTTP/1.1" 200 2988
[2019-11-18 18:11:51,290] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:11:51,313] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:11:55,579] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/users/trole/
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1568, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1286, in response_action
    response = func(self, request, queryset)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/actions.py", line 37, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 172, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 232, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 216, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 218, in _nested
    ret = [format_callback(obj)]
  File "/home/tarena/.local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 145, in format_callback
    force_text(obj))
  File "/home/tarena/.local/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/home/tarena/桌面/git/Storage/server/storage/users/models.py", line 41, in __str__
    return self.name
AttributeError: 'TUser' object has no attribute 'name'
[2019-11-18 18:11:55,630] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /admin/users/trole/ HTTP/1.1" 500 151430
[2019-11-18 18:11:56,928] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/ HTTP/1.1" 200 5205
[2019-11-18 18:12:04,465] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/trole/add/ HTTP/1.1" 200 6840
[2019-11-18 18:12:04,497] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:13:30,489] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 10576
[2019-11-18 18:13:30,526] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:17:21,878] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:17:23,036] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:17:26,086] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:17:26,385] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:17:26,606] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:17:26,840] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:21:05,416] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:21:07,024] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:22:29,653] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:22:31,664] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:22:33,086] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:22:52,077] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:23:43,679] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:23:55,639] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:24:14,579] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:25:03,523] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:25:09,034] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:25:39,104] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:26:16,455] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/role?page=1 HTTP/1.1" 200 0
[2019-11-18 18:26:16,461] [LinqHelper.py:53] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'is_active' into field. Choices are: created_time, description, id, name, parent_role, right, right_id, tuser
[2019-11-18 18:26:16,461] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/role
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 122, in get
    res['data'] = LinqHelper.res_format(code, data.page(page).object_list)['data']
AttributeError: 'str' object has no attribute 'page'
[2019-11-18 18:26:16,506] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/role?page=1 HTTP/1.1" 500 82944
[2019-11-18 18:26:26,416] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:27:02,932] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 18:27:29,194] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:27:41,929] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:27:49,617] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:28:43,911] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:28:46,026] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 18:29:19,657] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:29:21,274] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 18:30:34,100] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:30:38,008] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /v1/users/user HTTP/1.1" 200 62
[2019-11-18 18:33:22,231] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:33:33,413] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:33:38,598] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:34:15,833] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:43:09,832] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type?_=1574073789734 HTTP/1.1" 200 77
[2019-11-18 18:46:40,912] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8682
[2019-11-18 18:46:44,876] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 3661
[2019-11-18 18:46:44,902] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:46:44,912] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/img/search.svg HTTP/1.1" 304 0
[2019-11-18 18:46:47,290] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6503
[2019-11-18 18:46:47,322] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:46:53,756] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 3661
[2019-11-18 18:46:54,702] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8682
[2019-11-18 18:46:56,390] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 3105
[2019-11-18 18:46:56,419] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:46:57,619] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/add/ HTTP/1.1" 200 4330
[2019-11-18 18:46:57,660] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:46:59,965] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 3105
[2019-11-18 18:47:00,541] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8682
[2019-11-18 18:47:01,345] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 3661
[2019-11-18 18:47:01,376] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:03,079] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6503
[2019-11-18 18:47:03,112] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:11,744] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 3661
[2019-11-18 18:47:15,967] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8682
[2019-11-18 18:47:17,085] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 3105
[2019-11-18 18:47:17,118] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:18,254] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/add/ HTTP/1.1" 200 4330
[2019-11-18 18:47:18,282] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:22,491] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/baseclass/add/ HTTP/1.1" 302 0
[2019-11-18 18:47:22,544] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 5118
[2019-11-18 18:47:22,579] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:30,117] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/add/ HTTP/1.1" 200 4330
[2019-11-18 18:47:32,062] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/ HTTP/1.1" 200 3088
[2019-11-18 18:47:33,298] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 4938
[2019-11-18 18:47:33,328] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:35,064] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/ HTTP/1.1" 200 3088
[2019-11-18 18:47:36,116] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 3661
[2019-11-18 18:47:36,149] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:38,189] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:47:38,234] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:52,042] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 302 0
[2019-11-18 18:47:52,117] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 6100
[2019-11-18 18:47:52,152] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:47:54,761] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:47:54,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:48:12,020] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/user?page=1 HTTP/1.1" 200 0
[2019-11-18 18:48:12,069] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 18:48:56,150] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8689
[2019-11-18 18:48:58,274] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 4938
[2019-11-18 18:48:58,304] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:49:00,505] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8689
[2019-11-18 18:49:01,458] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 5921
[2019-11-18 18:49:01,493] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:49:08,834] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/1/change/ HTTP/1.1" 200 6763
[2019-11-18 18:49:08,866] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:49:14,238] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/1/change/ HTTP/1.1" 302 0
[2019-11-18 18:49:14,281] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 6100
[2019-11-18 18:49:14,318] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:49:29,257] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type?_=1574074169144 HTTP/1.1" 200 302
[2019-11-18 18:49:29,440] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type?_=1574074169371 HTTP/1.1" 200 302
[2019-11-18 18:49:57,313] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:49:57,341] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:50:11,405] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 5921
[2019-11-18 18:50:13,098] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8695
[2019-11-18 18:50:14,602] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 5921
[2019-11-18 18:50:14,632] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:50:16,333] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:50:16,368] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:50:25,418] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 5921
[2019-11-18 18:50:25,455] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:50:51,362] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:50:51,391] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:51:05,084] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 200 6704
[2019-11-18 18:51:05,107] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:51:10,571] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 302 0
[2019-11-18 18:51:10,613] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6784
[2019-11-18 18:51:10,636] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:51:31,022] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:51:32,219] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/ HTTP/1.1" 200 3088
[2019-11-18 18:51:34,274] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 4938
[2019-11-18 18:51:34,296] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:51:36,259] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8704
[2019-11-18 18:51:39,411] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 4938
[2019-11-18 18:51:39,444] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:51:42,152] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8704
[2019-11-18 18:51:43,709] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 6449
[2019-11-18 18:51:43,742] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:51:55,900] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/2/change/ HTTP/1.1" 200 6775
[2019-11-18 18:51:55,930] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:52:02,792] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/2/change/ HTTP/1.1" 302 0
[2019-11-18 18:52:02,836] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 6622
[2019-11-18 18:52:02,870] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:52:07,005] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:52:07,036] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:52:15,340] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 302 0
[2019-11-18 18:52:15,418] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 7084
[2019-11-18 18:52:15,445] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:52:16,536] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:52:16,570] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:52:25,428] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8713
[2019-11-18 18:52:28,100] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/baseclass/ HTTP/1.1" 200 4938
[2019-11-18 18:52:28,133] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:52:29,728] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8713
[2019-11-18 18:52:30,678] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/ HTTP/1.1" 200 6905
[2019-11-18 18:52:30,709] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:52:37,005] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6540
[2019-11-18 18:52:37,038] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:53:04,342] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 302 0
[2019-11-18 18:53:04,386] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6778
[2019-11-18 18:53:04,411] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:53:11,277] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 200 6698
[2019-11-18 18:53:11,315] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:53:15,391] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 302 0
[2019-11-18 18:53:15,439] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6778
[2019-11-18 18:53:15,474] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:53:27,681] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 302 0
[2019-11-18 18:53:27,727] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6778
[2019-11-18 18:53:27,752] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:53:38,158] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 200 6698
[2019-11-18 18:53:38,183] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:53:41,105] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/dict_con/basetype/add/ HTTP/1.1" 302 0
[2019-11-18 18:53:41,153] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/dict_con/basetype/add/ HTTP/1.1" 200 6778
[2019-11-18 18:53:41,187] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:54:03,910] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 8725
[2019-11-18 18:54:05,795] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 10576
[2019-11-18 18:54:05,820] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:58:08,862] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 10576
[2019-11-18 18:58:08,891] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:58:10,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 10576
[2019-11-18 18:58:10,826] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:58:11,116] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 10576
[2019-11-18 18:58:11,137] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:11,268] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14118
[2019-11-18 18:59:11,294] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:12,334] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14118
[2019-11-18 18:59:12,367] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:22,871] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/20/change/ HTTP/1.1" 200 6858
[2019-11-18 18:59:22,902] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:26,968] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/20/change/ HTTP/1.1" 302 0
[2019-11-18 18:59:27,052] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14299
[2019-11-18 18:59:27,088] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:29,458] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/19/change/ HTTP/1.1" 200 6858
[2019-11-18 18:59:29,491] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:31,822] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/19/change/ HTTP/1.1" 302 0
[2019-11-18 18:59:31,918] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14304
[2019-11-18 18:59:31,959] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:33,452] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/18/change/ HTTP/1.1" 200 6858
[2019-11-18 18:59:33,493] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:36,238] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/18/change/ HTTP/1.1" 302 0
[2019-11-18 18:59:36,322] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14309
[2019-11-18 18:59:36,368] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:37,515] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/14/change/ HTTP/1.1" 200 6858
[2019-11-18 18:59:37,548] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:39,856] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/14/change/ HTTP/1.1" 302 0
[2019-11-18 18:59:39,937] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14314
[2019-11-18 18:59:39,973] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:45,323] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/2/change/ HTTP/1.1" 200 6853
[2019-11-18 18:59:45,345] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:47,561] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/2/change/ HTTP/1.1" 302 0
[2019-11-18 18:59:47,652] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14318
[2019-11-18 18:59:47,689] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:49,099] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/5/change/ HTTP/1.1" 200 6850
[2019-11-18 18:59:49,134] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:51,516] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/5/change/ HTTP/1.1" 302 0
[2019-11-18 18:59:51,595] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14323
[2019-11-18 18:59:51,635] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:53,449] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/13/change/ HTTP/1.1" 200 6861
[2019-11-18 18:59:53,485] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:55,579] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/13/change/ HTTP/1.1" 302 0
[2019-11-18 18:59:55,685] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14329
[2019-11-18 18:59:55,720] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 18:59:57,079] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/16/change/ HTTP/1.1" 200 6852
[2019-11-18 18:59:57,118] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:00,783] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/16/change/ HTTP/1.1" 302 0
[2019-11-18 19:00:00,897] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14334
[2019-11-18 19:00:00,932] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:02,379] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/18/change/ HTTP/1.1" 200 6858
[2019-11-18 19:00:02,410] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:04,619] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/18/change/ HTTP/1.1" 302 0
[2019-11-18 19:00:04,715] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14334
[2019-11-18 19:00:04,749] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:05,660] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 14985
[2019-11-18 19:00:05,706] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:05,761] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
[2019-11-18 19:00:07,933] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/17/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6933
[2019-11-18 19:00:07,972] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:10,583] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/17/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:10,671] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15166
[2019-11-18 19:00:10,713] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:11,918] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/12/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6942
[2019-11-18 19:00:11,954] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:14,078] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/12/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:14,180] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15171
[2019-11-18 19:00:14,214] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:15,430] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/15/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6939
[2019-11-18 19:00:15,464] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:17,643] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/15/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:17,748] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15176
[2019-11-18 19:00:17,777] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:18,790] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/11/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6936
[2019-11-18 19:00:18,826] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:21,071] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/11/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:21,163] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15181
[2019-11-18 19:00:21,197] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:22,590] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/9/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6937
[2019-11-18 19:00:22,622] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:25,240] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/9/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:25,341] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15185
[2019-11-18 19:00:25,366] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:26,475] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/10/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6942
[2019-11-18 19:00:26,510] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:28,696] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/10/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:28,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15191
[2019-11-18 19:00:28,833] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:32,915] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/8/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6931
[2019-11-18 19:00:32,954] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:36,274] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/8/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:36,370] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15195
[2019-11-18 19:00:36,397] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:37,922] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/7/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6937
[2019-11-18 19:00:37,961] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:40,031] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/7/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:40,138] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15200
[2019-11-18 19:00:40,174] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:41,559] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/6/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6937
[2019-11-18 19:00:41,586] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:44,042] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/6/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:44,150] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15205
[2019-11-18 19:00:44,191] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:45,374] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/4/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6928
[2019-11-18 19:00:45,414] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:47,132] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/4/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:47,271] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15210
[2019-11-18 19:00:47,302] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:48,709] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/3/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6928
[2019-11-18 19:00:48,742] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:50,867] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/3/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:50,982] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15215
[2019-11-18 19:00:51,025] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:52,344] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/1/change/?_changelist_filters=o%3D4 HTTP/1.1" 200 6923
[2019-11-18 19:00:52,380] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:00:54,389] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /admin/users/tright/1/change/?_changelist_filters=o%3D4 HTTP/1.1" 302 0
[2019-11-18 19:00:54,487] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/?o=4 HTTP/1.1" 200 15220
[2019-11-18 19:00:54,523] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:03:33,787] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14218
[2019-11-18 19:03:33,820] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:03:34,174] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14218
[2019-11-18 19:03:34,210] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:03:34,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14218
[2019-11-18 19:03:34,558] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:03:34,868] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14218
[2019-11-18 19:03:34,899] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:04:38,038] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/user?page=1 HTTP/1.1" 200 0
[2019-11-18 19:04:38,084] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/user?page=1 HTTP/1.1" 200 398
[2019-11-18 19:24:22,657] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/users/tright/ HTTP/1.1" 200 14218
[2019-11-18 19:24:22,693] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7682
[2019-11-18 19:31:28,772] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 2446
[2019-11-18 19:33:51,962] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 2446
[2019-11-18 19:34:24,013] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/right HTTP/1.1" 200 0
[2019-11-18 19:34:24,046] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 2446
[2019-11-18 19:34:53,886] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:41:01,466] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/type
[2019-11-18 19:41:01,467] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/type HTTP/1.1" 404 2681
[2019-11-18 19:41:24,837] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/type
[2019-11-18 19:41:24,838] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/type HTTP/1.1" 404 2681
[2019-11-18 19:41:43,472] [base.py:152] [base:get_response] [WARNING]- Not Found: /v1/users/type
[2019-11-18 19:41:43,474] [basehttp.py:124] [basehttp:log_message] [WARNING]- "GET /v1/users/type HTTP/1.1" 404 2681
[2019-11-18 19:42:01,605] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/dict_con/type
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/dict_con/views.py", line 118, in get
    'is_active': i.is_active,
AttributeError: 'BaseType' object has no attribute 'is_active'
[2019-11-18 19:42:01,820] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/dict_con/type HTTP/1.1" 500 82097
[2019-11-18 19:42:07,966] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/dict_con/type
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/dict_con/views.py", line 118, in get
    'is_active': i.is_active,
AttributeError: 'BaseType' object has no attribute 'is_active'
[2019-11-18 19:42:08,011] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/dict_con/type HTTP/1.1" 500 83292
[2019-11-18 19:42:23,274] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:43:30,604] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:43:30,613] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/dict_con/type HTTP/1.1" 200 0
[2019-11-18 19:43:30,655] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:45:53,048] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:45:53,081] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:45:53,805] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:45:53,847] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:46:16,512] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:46:16,555] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:46:22,753] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:46:22,805] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:46:23,461] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:46:23,510] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:47:06,418] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:47:06,499] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:48:19,289] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:48:19,372] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:48:26,819] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:48:26,918] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:48:51,013] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:48:51,108] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:48:51,705] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:48:51,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:49:03,366] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:49:03,470] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:49:16,656] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:49:16,755] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:49:26,404] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:49:26,476] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:50:07,450] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:50:07,528] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:51:00,819] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:51:00,908] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:51:50,604] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:51:50,690] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:51:51,623] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:51:51,710] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:52:09,315] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:52:09,405] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:55:56,976] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:55:57,050] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:56:15,210] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:56:15,306] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:56:42,561] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:56:42,636] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:56:56,047] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:56:56,131] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:57:13,075] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:57:13,155] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 19:58:11,149] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 19:58:11,237] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:00:37,550] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:00:37,642] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:04:05,268] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:04:05,335] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:05:17,665] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:05:17,759] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:05:49,524] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:05:49,586] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:07:47,454] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:07:47,559] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:08:21,012] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:08:21,097] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:09:50,627] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:09:50,696] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:10:04,508] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:10:04,606] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:10:47,740] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:10:47,815] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:11:29,892] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:11:29,967] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:12:38,078] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:12:38,156] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:12:50,035] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:12:50,104] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:14:48,869] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:14:48,933] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:18:16,348] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:18:16,418] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:18:17,458] [base.py:93] [base:http_method_not_allowed] [WARNING]- Method Not Allowed (PUT): /v1/users/right
[2019-11-18 20:18:17,459] [basehttp.py:124] [basehttp:log_message] [WARNING]- "PUT /v1/users/right HTTP/1.1" 405 0
[2019-11-18 20:18:44,633] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:18:44,690] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:18:45,476] [base.py:93] [base:http_method_not_allowed] [WARNING]- Method Not Allowed (PUT): /v1/users/right
[2019-11-18 20:18:45,476] [basehttp.py:124] [basehttp:log_message] [WARNING]- "PUT /v1/users/right HTTP/1.1" 405 0
[2019-11-18 20:18:48,285] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:18:48,343] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:18:51,483] [base.py:93] [base:http_method_not_allowed] [WARNING]- Method Not Allowed (PUT): /v1/users/right
[2019-11-18 20:18:51,484] [basehttp.py:124] [basehttp:log_message] [WARNING]- "PUT /v1/users/right HTTP/1.1" 405 0
[2019-11-18 20:21:09,589] [basehttp.py:124] [basehttp:log_message] [INFO]- "PUT /v1/users/right HTTP/1.1" 200 12
[2019-11-18 20:23:43,230] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:23:43,304] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:23:45,442] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:23:45,513] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:23:48,438] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:23:48,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:24:21,689] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:24:52,138] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:25:06,729] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 150, in put
    arr.push({
AttributeError: 'list' object has no attribute 'push'
[2019-11-18 20:25:06,798] [basehttp.py:124] [basehttp:log_message] [ERROR]- "PUT /v1/users/right HTTP/1.1" 500 82250
[2019-11-18 20:25:35,484] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:25:35,559] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:26:55,152] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:27:04,747] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1606
[2019-11-18 20:27:47,216] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 145, in get
    return JsonResponse({'data': res})
  File "/home/tarena/.local/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'BaseType' is not JSON serializable
[2019-11-18 20:27:47,346] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right HTTP/1.1" 500 135153
[2019-11-18 20:27:47,412] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:27:49,887] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 145, in get
    return JsonResponse({'data': res})
  File "/home/tarena/.local/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'BaseType' is not JSON serializable
[2019-11-18 20:27:49,959] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right HTTP/1.1" 500 135467
[2019-11-18 20:27:50,043] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:27:50,683] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 145, in get
    return JsonResponse({'data': res})
  File "/home/tarena/.local/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'BaseType' is not JSON serializable
[2019-11-18 20:27:50,747] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right HTTP/1.1" 500 135467
[2019-11-18 20:27:50,835] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:28:21,760] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 146, in get
    return JsonResponse({'data': res})
  File "/home/tarena/.local/lib/python3.6/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'BaseType' is not JSON serializable
[2019-11-18 20:28:21,840] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /v1/users/right HTTP/1.1" 500 134555
[2019-11-18 20:28:58,609] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1826
[2019-11-18 20:29:06,677] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1826
[2019-11-18 20:29:06,751] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:29:09,686] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 152, in put
    arr.push({
AttributeError: 'list' object has no attribute 'push'
[2019-11-18 20:29:09,738] [basehttp.py:124] [basehttp:log_message] [ERROR]- "PUT /v1/users/right HTTP/1.1" 500 82270
[2019-11-18 20:31:10,194] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:31:10,249] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:31:17,107] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 151, in put
    arr.push({
AttributeError: 'list' object has no attribute 'push'
[2019-11-18 20:31:17,161] [basehttp.py:124] [basehttp:log_message] [ERROR]- "PUT /v1/users/right HTTP/1.1" 500 82364
[2019-11-18 20:33:20,814] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:33:20,875] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:33:31,086] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /v1/users/right
Traceback (most recent call last):
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tarena/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/tarena/桌面/git/Storage/server/storage/users/views.py", line 151, in put
    arr.push({
AttributeError: 'list' object has no attribute 'push'
[2019-11-18 20:33:31,123] [basehttp.py:124] [basehttp:log_message] [ERROR]- "PUT /v1/users/right HTTP/1.1" 500 83361
[2019-11-18 20:37:16,302] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:37:16,364] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:38:12,200] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:38:12,275] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:38:24,219] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:38:24,296] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:38:28,702] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:38:28,795] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:38:33,699] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:38:33,804] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:39:38,470] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:39:38,546] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:48:03,075] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/dict_con/type HTTP/1.1" 200 0
[2019-11-18 20:48:03,386] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:48:09,302] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:49:23,690] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/right HTTP/1.1" 200 0
[2019-11-18 20:49:23,739] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:49:23,772] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:06,689] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:06,718] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:10,859] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:10,885] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:23,845] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:23,875] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:24,528] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:24,541] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:24,884] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:24,911] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:25,135] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:25,156] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:25,398] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:25,430] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:25,773] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:25,788] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:26,180] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:26,209] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:38,092] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:38,112] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:55,306] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:55,347] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:50:56,123] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:50:56,162] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:51:03,407] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:51:03,432] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:51:07,358] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:51:07,373] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:51:20,919] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:51:20,942] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:51:21,492] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:51:21,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:51:30,271] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:51:30,312] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:51:38,867] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:51:38,894] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:52:27,422] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:52:27,463] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:53:17,566] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:53:17,593] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:54:27,368] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:54:27,403] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:57:11,886] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:57:11,930] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:59:24,740] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/right HTTP/1.1" 200 0
[2019-11-18 20:59:24,775] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:59:24,783] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/dict_con/type HTTP/1.1" 200 0
[2019-11-18 20:59:24,797] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 20:59:25,625] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 20:59:25,643] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:00:44,274] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:00:44,295] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:01:32,556] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:01:32,585] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:02:13,794] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:02:13,811] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:02:23,943] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:02:23,969] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:03:23,903] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:03:23,926] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:03:30,047] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:03:30,063] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:03:47,702] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:03:47,749] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:04:07,759] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:04:07,771] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:04:45,121] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:04:45,154] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:04:58,532] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:04:58,567] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:05:08,368] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:05:08,396] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:05:22,406] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:05:22,432] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:05:27,542] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:05:27,570] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:05:35,721] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:05:35,781] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:06:05,981] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:06:05,995] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:06:26,353] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:06:26,396] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:06:35,913] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:06:35,947] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:12:16,821] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:12:16,846] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:13:40,682] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:13:40,706] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:15:24,021] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/right HTTP/1.1" 200 0
[2019-11-18 21:15:24,049] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:15:24,057] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/dict_con/type HTTP/1.1" 200 0
[2019-11-18 21:15:24,078] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:15:25,149] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:15:25,171] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:17:01,704] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/users/right HTTP/1.1" 200 0
[2019-11-18 21:17:01,739] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:17:01,748] [basehttp.py:124] [basehttp:log_message] [INFO]- "OPTIONS /v1/dict_con/type HTTP/1.1" 200 0
[2019-11-18 21:17:01,766] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
[2019-11-18 21:17:03,311] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/users/right HTTP/1.1" 200 1586
[2019-11-18 21:17:03,331] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /v1/dict_con/type HTTP/1.1" 200 1447
